﻿version: '2'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/share/nginx/html
  webpack:
    image: webpack:alpine
    container_name: webpack
    ports:
      - "35729:35729" 
    volumes:
      - ./app:/app
